name: Run performance scans

on:
  workflow_dispatch: # enable run button on github.com
  schedule:
    - cron: "0 2 * * *" # Run daily at 2:00am

jobs:
  scan:
    name: Performance scan
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: "./package-lock.json"
      - name: Install dependencies
        run: npm install
      - name: Run scans
        run: npm run test-pages
      - name: Build report site
        run: npm run build
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Commit report to repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all
          git commit -m ":chart_with_downwards_trend: performance report from ${{ env.NOW }}"
          git push
